=== random-zh/program-rcpsp-nsga2-mtpc-stc/data/rcmpsp/mp.dtd
<!ELEMENT mp-list (mp)>
<!ELEMENT mp (name,project-list,resources)>
<!ELEMENT project-list (project)+>
<!ELEMENT project (filename,start)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT resources (resource,resource,resource,resource)>
<!ELEMENT resource (#PCDATA)>
<!ELEMENT resource (#PCDATA)>
<!ELEMENT resource (#PCDATA)>
<!ELEMENT resource (#PCDATA)>

=== random-zh/program-rcpsp-nsga2-mtpc-stc/data/rcmpsp/mp_j90_a5_nr4.xml
<!DOCTYPE mp-list SYSTEM "mp.dtd">
<mp-list>
	<mp>
		<name>mp_j90_a5_nr4</name>
		<project-list>
			<project>
				<filename>KolischInstanzen/j90/j901_2.sm</filename>
				<start>0</start>
			</project>
			<project>
				<filename>KolischInstanzen/j90/j905_5.sm</filename>
				<start>5</start>
			</project>
			<project>
				<filename>KolischInstanzen/j90/j906_10.sm</filename>
				<start>10</start>
			</project>
			<project>
				<filename>KolischInstanzen/j90/j907_10.sm</filename>
				<start>25</start>
			</project>
			<project>
				<filename>KolischInstanzen/j90/j908_10.sm</filename>
				<start>30</start>
			</project>
		</project-list>
		<resources>
			<resource>88</resource>
			<resource>72</resource>
			<resource>77</resource>
			<resource>0</resource>
		</resources>
	</mp>
</mp-list>
